name: todolist
description: TODO app by genx team

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_ringtone_player: null
  get: null
  hive: null
  line_awesome_flutter: null
  modal_bottom_sheet: null
  path_provider: null
  percent_indicator: null
  shared_preferences: null
  sqflite: null
  table_calendar: ^2.3.0

dependency_overrides:
  intl: 0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
